version: '3.1'
services:
    adminer:
        image: adminer
        ports:
            - 8080:8080
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password --innodb_use_native_aio=0
        environment:
            MYSQL_ROOT_PASSWORD: it635
        volumes:
            - ./db:/docker-entrypoint-initdb.d
    php:
        build: php-apache-mysqli
        ports:
            - 8888:80
        volumes:
            - ./www:/var/www/html/        
